import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#e0f2f1" },
  header: { padding: 20, alignItems: "center", flexDirection: "row" },
  headerTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#004d40",
    letterSpacing: 1,
  },
  card: {
    margin: 15,
    backgroundColor: "white",
    borderRadius: 15,
    overflow: "hidden",
    elevation: 5,
  },
  alertText: {
    color: "white",
    fontWeight: "bold",
    marginLeft: 10,
    fontSize: 12,
  },
  content: { padding: 20 },
  titleSection: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 20,
  },
  exclamation: { color: "white", fontSize: 30, fontWeight: "bold" },
  reportTitle: { fontSize: 20, fontWeight: "bold", color: "#333" },
  reportId: { color: "#666" },
  section: { marginBottom: 20 },
  sectionTitle: {
    fontSize: 14,
    fontWeight: "bold",
    color: "#004d40",
    marginBottom: 10,
  },
  row: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 10,
    borderBottomWidth: 1,
    borderBottomColor: "#eee",
    paddingBottom: 5,
  },
  label: { fontSize: 12, color: "#888" },
  value: { fontSize: 14, color: "#333" },
  statusBadge: { flexDirection: "row", alignItems: "center" },

  feedbackBox: {
    backgroundColor: "#f9f9f9",
    padding: 12,
    borderRadius: 8,
    borderLeftWidth: 4,
    borderLeftColor: "#004d40",
  },
  feedbackText: { fontStyle: "italic", color: "#444", lineHeight: 20 },
  quoteBox: {
    backgroundColor: "#fff",
    borderWidth: 1,
    borderColor: "#ddd",
    padding: 10,
    borderRadius: 8,
    marginBottom: 8,
  },
  quote: { fontSize: 13, color: "#555" },
  button: {
    marginTop: 10,
    padding: 15,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#ccc",
    alignItems: "center",
  },
  buttonText: { fontWeight: "640", color: "#333" },
  Img: {
    width: 80,
    height: 80,
    resizeMode: "contain",
  },
  disclaimerContainer: {
    paddingHorizontal: 20,
    paddingVertical: 15,
    marginTop: 10,
    marginBottom: 20,
    borderTopWidth: 1,
    borderTopColor: "#eeeeee",
  },
  disclaimerText: {
    fontSize: 11,
    color: "#7f8c8d",
    textAlign: "justify",
    lineHeight: 16,
    letterSpacing: 0.3,
  },
  emergencyCard: {
    backgroundColor: "#fff",
    margin: 15,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: "#d32f2f", // El rojo de crisis que ya usas
    overflow: "hidden",
    elevation: 4,
  },
  emergencyHeader: {
    backgroundColor: "#d32f2f",
    flexDirection: "row",
    padding: 10,
    alignItems: "center",
    justifyContent: "center",
  },
  emergencyTitle: {
    color: "#fff",
    fontWeight: "bold",
    marginLeft: 8,
    fontSize: 14,
  },
  emergencyBody: {
    padding: 15,
  },
  emergencySubtitle: {
    fontSize: 13,
    color: "#333",
    fontWeight: "600",
    marginBottom: 12,
    textAlign: "center",
  },
  phoneRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 8,
    paddingBottom: 4,
    borderBottomWidth: 1,
    borderBottomColor: "#f0f0f0",
  },
  phoneLabel: {
    fontSize: 12,
    color: "#666",
  },
  phoneNumber: {
    fontSize: 13,
    fontWeight: "bold",
    color: "#d32f2f",
  },
  emergencyNote: {
    fontSize: 11,
    fontStyle: "italic",
    color: "#888",
    marginTop: 10,
    textAlign: "center",
  },
});
