import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F7FAFC',
  },
  content: {
    paddingBottom: 40,
  },
  header: {
    alignItems: 'center',
    paddingVertical: 40,
    backgroundColor: '#FFFFFF',
    borderBottomLeftRadius: 40,
    borderBottomRightRadius: 40,
    elevation: 5,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 10,
  },
  iconCircle: {
    width: 140,
    height: 140,
    borderRadius: 70,
    backgroundColor: '#F0EFFF',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 20,
    borderWidth: 2,
    borderColor: '#E2E8F0',
  },
  mainTitle: {
    fontSize: 26,
    fontWeight: 'bold',
    color: '#2D3748',
    textAlign: 'center',
  },
  subtitle: {
    fontSize: 16,
    color: '#718096',
    marginTop: 10,
    textAlign: 'center',
    paddingHorizontal: 40,
  },
  formCard: {
    margin: 20,
    padding: 25,
    backgroundColor: '#FFFFFF',
    borderRadius: 25,
    elevation: 3,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 5,
  },
  label: {
    fontSize: 17,
    fontWeight: '700',
    color: '#4A5568',
    marginBottom: 15,
  },
  sliderContainer: {
    flexDirection: 'row',
    width:"100%",
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  track: {
    height: 8,
    borderRadius: 4,
    width: '80%',
  },
  thumb: {
    height: 25,
    width: 25,
    backgroundColor: '#80eff9',
    borderWidth: 3,
    borderColor: '#FFF',
  },
  levelBadge: {
    backgroundColor: '#80eff9',
    width: 45,
    height: 45,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
  },
  levelText: {
    color: '#FFF',
    fontSize: 20,
    fontWeight: 'bold',
  },
  helperText: {
    fontSize: 12,
    color: '#A0AEC0',
    marginTop: 5,
    textAlign: 'left',
  },
  textArea: {
    backgroundColor: '#F7FAFC',
    borderRadius: 15,
    padding: 15,
    height: 120,
    textAlignVertical: 'top',
    fontSize: 16,
    color: '#2D3748',
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  sendButton: {
    backgroundColor: '#80eff9',
    borderRadius: 15,
    paddingVertical: 18,
    marginTop: 35,
    alignItems: 'center',
    elevation: 4,
  },
  sendButtonText: {
    
    fontSize: 18,
    fontWeight: 'bold',
    letterSpacing: 1.5,
  },
  individualButton:{
    backgroundColor: '#fff',
  borderWidth: 1,
  borderColor: '#ddd',
  borderRadius: 22, 
  marginHorizontal: 5,
  },buttonGroupContainer:{
    flex:2,
    height: 45,
  width: '50%',
  backgroundColor: 'transparent',
  borderWidth: 0, 
  marginVertical: 0,
  },selectedButton:{
    
  backgroundColor: '#80eff9',
  borderColor: '#80eff9',
  },
  
});